// <auto-generated />
using System;
using Featly.Storage.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Featly.Storage.SqlServer.Migrations
{
    [DbContext(typeof(FeatlyDbContext))]
    [Migration("20260729095229_AddApprovalApiKeysAndSettings")]
    partial class AddApprovalApiKeysAndSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Featly.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("Prefix");

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("Featly.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowEmergencyBypass")
                        .HasColumnType("bit");

                    b.Property<bool>("AuthorCanApproveOwnChange")
                        .HasColumnType("bit");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinApprovals")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId")
                        .IsUnique();

                    b.ToTable("ApprovalPolicies", (string)null);
                });

            modelBuilder.Entity("Featly.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Configs", (string)null);
                });

            modelBuilder.Entity("Featly.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ConfigVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("Featly.Flag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DefaultVariantKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Flags", (string)null);
                });

            modelBuilder.Entity("Featly.PendingChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AppliedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProposedState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("ScheduledApplyAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("WasEmergencyBypass")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "ScheduledApplyAt");

                    b.ToTable("PendingChanges", (string)null);
                });

            modelBuilder.Entity("Featly.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Featly.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Featly.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssigneeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("Featly.RoleUpgradeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Justification")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("RequestedRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("TargetEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUpgradeRequests", (string)null);
                });

            modelBuilder.Entity("Featly.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Segments", (string)null);
                });

            modelBuilder.Entity("Featly.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("Featly.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Featly.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.PrimitiveCollection<string>("MemberUserIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("Featly.ApprovalPolicy", b =>
                {
                    b.OwnsMany("Featly.ApproverRule", "ApproverRules", b1 =>
                        {
                            b1.Property<Guid>("ApprovalPolicyId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid?>("GroupId");

                            b1.Property<Guid>("Id");

                            b1.Property<bool>("Mandatory");

                            b1.Property<int>("MinFromThisRule");

                            b1.Property<Guid?>("RoleId");

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.Property<Guid?>("UserId");

                            b1.HasKey("ApprovalPolicyId", "__synthesizedOrdinal");

                            b1.ToTable("ApprovalPolicies");

                            b1
                                .ToJson("ApproverRules")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ApprovalPolicyId");
                        });

                    b.Navigation("ApproverRules");
                });

            modelBuilder.Entity("Featly.Config", b =>
                {
                    b.OwnsMany("Featly.ConfigRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("ConfigId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Enabled");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256);

                            b1.Property<int>("Order");

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ConfigId", "__synthesizedOrdinal");

                            b1.ToTable("Configs");

                            b1
                                .ToJson("Rules")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ConfigId");

                            b1.OwnsMany("Featly.Condition", "Conditions", b2 =>
                                {
                                    b2.Property<Guid>("ConfigRuleConfigId");

                                    b2.Property<int>("ConfigRule__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Attribute")
                                        .IsRequired()
                                        .HasMaxLength(256);

                                    b2.Property<bool>("Negate");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(32);

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("ConfigRuleConfigId", "ConfigRule__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Configs");

                                    b2.WithOwner()
                                        .HasForeignKey("ConfigRuleConfigId", "ConfigRule__synthesizedOrdinal");
                                });

                            b1.Navigation("Conditions");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Featly.Flag", b =>
                {
                    b.OwnsMany("Featly.Prerequisite", "Prerequisites", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("FlagKey")
                                .IsRequired()
                                .HasMaxLength(128);

                            b1.PrimitiveCollection<string>("RequiredVariantKeys")
                                .IsRequired();

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1
                                .ToJson("Prerequisites")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");
                        });

                    b.OwnsMany("Featly.Rule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Enabled");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256);

                            b1.Property<int>("Order");

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1
                                .ToJson("Rules")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");

                            b1.OwnsMany("Featly.Condition", "Conditions", b2 =>
                                {
                                    b2.Property<Guid>("RuleFlagId");

                                    b2.Property<int>("Rule__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Attribute")
                                        .IsRequired()
                                        .HasMaxLength(256);

                                    b2.Property<bool>("Negate");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(32);

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("RuleFlagId", "Rule__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Flags");

                                    b2.WithOwner()
                                        .HasForeignKey("RuleFlagId", "Rule__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Featly.RuleOutcome", "Outcome", b2 =>
                                {
                                    b2.Property<Guid>("RuleFlagId");

                                    b2.Property<int>("Rule__synthesizedOrdinal");

                                    b2.Property<string>("VariantKey")
                                        .HasMaxLength(128);

                                    b2.HasKey("RuleFlagId", "Rule__synthesizedOrdinal");

                                    b2.ToTable("Flags");

                                    b2.WithOwner()
                                        .HasForeignKey("RuleFlagId", "Rule__synthesizedOrdinal");

                                    b2.OwnsMany("Featly.Split", "Splits", b3 =>
                                        {
                                            b3.Property<Guid>("RuleOutcomeRuleFlagId");

                                            b3.Property<int>("RuleOutcomeRule__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAddOrUpdate();

                                            b3.Property<string>("VariantKey")
                                                .IsRequired()
                                                .HasMaxLength(128);

                                            b3.Property<int>("Weight");

                                            b3.HasKey("RuleOutcomeRuleFlagId", "RuleOutcomeRule__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("Flags");

                                            b3.WithOwner()
                                                .HasForeignKey("RuleOutcomeRuleFlagId", "RuleOutcomeRule__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Splits");
                                });

                            b1.Navigation("Conditions");

                            b1.Navigation("Outcome")
                                .IsRequired();
                        });

                    b.OwnsMany("Featly.Variant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Description")
                                .HasMaxLength(2048);

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(128);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256);

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1
                                .ToJson("Variants")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");
                        });

                    b.Navigation("Prerequisites");

                    b.Navigation("Rules");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Featly.PendingChange", b =>
                {
                    b.OwnsMany("Featly.ChangeApproval", "Approvals", b1 =>
                        {
                            b1.Property<Guid>("PendingChangeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("ApproverUserId");

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<string>("Comment");

                            b1.Property<string>("Decision")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.HasKey("PendingChangeId", "__synthesizedOrdinal");

                            b1.ToTable("PendingChanges");

                            b1
                                .ToJson("Approvals")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PendingChangeId");
                        });

                    b.OwnsMany("Featly.ChangeComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("PendingChangeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<Guid>("AuthorUserId");

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.HasKey("PendingChangeId", "__synthesizedOrdinal");

                            b1.ToTable("PendingChanges");

                            b1
                                .ToJson("Comments")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PendingChangeId");
                        });

                    b.Navigation("Approvals");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Featly.Segment", b =>
                {
                    b.OwnsMany("Featly.Condition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("SegmentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Attribute")
                                .IsRequired()
                                .HasMaxLength(256);

                            b1.Property<bool>("Negate");

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(32);

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("SegmentId", "__synthesizedOrdinal");

                            b1.ToTable("Segments");

                            b1
                                .ToJson("Conditions")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("SegmentId");
                        });

                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
