// <auto-generated />
using System;
using Featly.Storage.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Featly.Storage.Sqlite.Migrations
{
    [DbContext(typeof(FeatlyDbContext))]
    [Migration("20260530101730_AddSegmentArchived")]
    partial class AddSegmentArchived
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Featly.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("Prefix");

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("Featly.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowEmergencyBypass")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AuthorCanApproveOwnChange")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinApprovals")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId")
                        .IsUnique();

                    b.ToTable("ApprovalPolicies", (string)null);
                });

            modelBuilder.Entity("Featly.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AssignedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId", "SubjectKey")
                        .IsUnique();

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("Featly.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EntityType", "EntityKey");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("Featly.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Configs", (string)null);
                });

            modelBuilder.Entity("Featly.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("Featly.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("SubjectKey");

                    b.HasIndex("EnvironmentId", "CustomKey");

                    b.HasIndex("EnvironmentId", "FlagKey");

                    b.HasIndex("EnvironmentId", "Type");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Featly.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hypothesis")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MetricKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StickyAssignments")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StoppedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Experiments", (string)null);
                });

            modelBuilder.Entity("Featly.Flag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultVariantKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Flags", (string)null);
                });

            modelBuilder.Entity("Featly.PendingChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AppliedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AppliedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentState")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyReason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RejectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasEmergencyBypass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("Status");

                    b.ToTable("PendingChanges", (string)null);
                });

            modelBuilder.Entity("Featly.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Featly.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Featly.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AssignedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("Featly.RoleUpgradeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DecidedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedRoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetEnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUpgradeRequests", (string)null);
                });

            modelBuilder.Entity("Featly.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Segments", (string)null);
                });

            modelBuilder.Entity("Featly.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Featly.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MemberUserIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("Featly.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WebhookEndpointId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEndpointId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("WebhookDeliveries", (string)null);
                });

            modelBuilder.Entity("Featly.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("EventTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("WebhookEndpoints", (string)null);
                });

            modelBuilder.Entity("Featly.ApprovalPolicy", b =>
                {
                    b.OwnsMany("Featly.ApproverRule", "ApproverRules", b1 =>
                        {
                            b1.Property<Guid>("ApprovalPolicyId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid?>("GroupId");

                            b1.Property<Guid>("Id");

                            b1.Property<bool>("Mandatory");

                            b1.Property<int>("MinFromThisRule");

                            b1.Property<Guid?>("RoleId");

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.Property<Guid?>("UserId");

                            b1.HasKey("ApprovalPolicyId", "__synthesizedOrdinal");

                            b1.ToTable("ApprovalPolicies");

                            b1.ToJson("ApproverRules");

                            b1.WithOwner()
                                .HasForeignKey("ApprovalPolicyId");
                        });

                    b.Navigation("ApproverRules");
                });

            modelBuilder.Entity("Featly.Config", b =>
                {
                    b.OwnsMany("Featly.ConfigRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("ConfigId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Enabled");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256);

                            b1.Property<int>("Order");

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ConfigId", "__synthesizedOrdinal");

                            b1.ToTable("Configs");

                            b1.ToJson("Rules");

                            b1.WithOwner()
                                .HasForeignKey("ConfigId");

                            b1.OwnsMany("Featly.Condition", "Conditions", b2 =>
                                {
                                    b2.Property<Guid>("ConfigRuleConfigId");

                                    b2.Property<int>("ConfigRule__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Attribute")
                                        .IsRequired()
                                        .HasMaxLength(256);

                                    b2.Property<bool>("Negate");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(32);

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("ConfigRuleConfigId", "ConfigRule__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Configs");

                                    b2.WithOwner()
                                        .HasForeignKey("ConfigRuleConfigId", "ConfigRule__synthesizedOrdinal");
                                });

                            b1.Navigation("Conditions");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Featly.Flag", b =>
                {
                    b.OwnsMany("Featly.Rule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Enabled");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256);

                            b1.Property<int>("Order");

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1.ToJson("Rules");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");

                            b1.OwnsMany("Featly.Condition", "Conditions", b2 =>
                                {
                                    b2.Property<Guid>("RuleFlagId");

                                    b2.Property<int>("Rule__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Attribute")
                                        .IsRequired()
                                        .HasMaxLength(256);

                                    b2.Property<bool>("Negate");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(32);

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("RuleFlagId", "Rule__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Flags");

                                    b2.WithOwner()
                                        .HasForeignKey("RuleFlagId", "Rule__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Featly.RuleOutcome", "Outcome", b2 =>
                                {
                                    b2.Property<Guid>("RuleFlagId");

                                    b2.Property<int>("Rule__synthesizedOrdinal");

                                    b2.Property<string>("VariantKey")
                                        .HasMaxLength(128);

                                    b2.HasKey("RuleFlagId", "Rule__synthesizedOrdinal");

                                    b2.ToTable("Flags");

                                    b2.WithOwner()
                                        .HasForeignKey("RuleFlagId", "Rule__synthesizedOrdinal");

                                    b2.OwnsMany("Featly.Split", "Splits", b3 =>
                                        {
                                            b3.Property<Guid>("RuleOutcomeRuleFlagId");

                                            b3.Property<int>("RuleOutcomeRule__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAddOrUpdate();

                                            b3.Property<string>("VariantKey")
                                                .IsRequired()
                                                .HasMaxLength(128);

                                            b3.Property<int>("Weight");

                                            b3.HasKey("RuleOutcomeRuleFlagId", "RuleOutcomeRule__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("Flags");

                                            b3.WithOwner()
                                                .HasForeignKey("RuleOutcomeRuleFlagId", "RuleOutcomeRule__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Splits");
                                });

                            b1.Navigation("Conditions");

                            b1.Navigation("Outcome")
                                .IsRequired();
                        });

                    b.OwnsMany("Featly.Variant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Description")
                                .HasMaxLength(2048);

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(128);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256);

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1.ToJson("Variants");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");
                        });

                    b.Navigation("Rules");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Featly.PendingChange", b =>
                {
                    b.OwnsMany("Featly.ChangeApproval", "Approvals", b1 =>
                        {
                            b1.Property<Guid>("PendingChangeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("ApproverUserId");

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<string>("Comment");

                            b1.Property<string>("Decision")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.HasKey("PendingChangeId", "__synthesizedOrdinal");

                            b1.ToTable("PendingChanges");

                            b1.ToJson("Approvals");

                            b1.WithOwner()
                                .HasForeignKey("PendingChangeId");
                        });

                    b.OwnsMany("Featly.ChangeComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("PendingChangeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<Guid>("AuthorUserId");

                            b1.Property<string>("Body")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.HasKey("PendingChangeId", "__synthesizedOrdinal");

                            b1.ToTable("PendingChanges");

                            b1.ToJson("Comments");

                            b1.WithOwner()
                                .HasForeignKey("PendingChangeId");
                        });

                    b.Navigation("Approvals");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Featly.Segment", b =>
                {
                    b.OwnsMany("Featly.Condition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("SegmentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Attribute")
                                .IsRequired()
                                .HasMaxLength(256);

                            b1.Property<bool>("Negate");

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(32);

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("SegmentId", "__synthesizedOrdinal");

                            b1.ToTable("Segments");

                            b1.ToJson("Conditions");

                            b1.WithOwner()
                                .HasForeignKey("SegmentId");
                        });

                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
