// <auto-generated />
using System;
using Featly.Storage.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Featly.Storage.Sqlite.Migrations
{
    [DbContext(typeof(FeatlyDbContext))]
    [Migration("20260526185818_ConvertTimestampsToUtcTicks")]
    partial class ConvertTimestampsToUtcTicks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Featly.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Configs", (string)null);
                });

            modelBuilder.Entity("Featly.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("Featly.Flag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultVariantKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Flags", (string)null);
                });

            modelBuilder.Entity("Featly.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Featly.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Segments", (string)null);
                });

            modelBuilder.Entity("Featly.Config", b =>
                {
                    b.OwnsMany("Featly.ConfigRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("ConfigId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Enabled");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256);

                            b1.Property<int>("Order");

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ConfigId", "__synthesizedOrdinal");

                            b1.ToTable("Configs");

                            b1.ToJson("Rules");

                            b1.WithOwner()
                                .HasForeignKey("ConfigId");

                            b1.OwnsMany("Featly.Condition", "Conditions", b2 =>
                                {
                                    b2.Property<Guid>("ConfigRuleConfigId");

                                    b2.Property<int>("ConfigRule__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Attribute")
                                        .IsRequired()
                                        .HasMaxLength(256);

                                    b2.Property<bool>("Negate");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(32);

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("ConfigRuleConfigId", "ConfigRule__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Configs");

                                    b2.WithOwner()
                                        .HasForeignKey("ConfigRuleConfigId", "ConfigRule__synthesizedOrdinal");
                                });

                            b1.Navigation("Conditions");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Featly.Flag", b =>
                {
                    b.OwnsMany("Featly.Rule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Enabled");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256);

                            b1.Property<int>("Order");

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1.ToJson("Rules");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");

                            b1.OwnsMany("Featly.Condition", "Conditions", b2 =>
                                {
                                    b2.Property<Guid>("RuleFlagId");

                                    b2.Property<int>("Rule__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Attribute")
                                        .IsRequired()
                                        .HasMaxLength(256);

                                    b2.Property<bool>("Negate");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(32);

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("RuleFlagId", "Rule__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Flags");

                                    b2.WithOwner()
                                        .HasForeignKey("RuleFlagId", "Rule__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Featly.RuleOutcome", "Outcome", b2 =>
                                {
                                    b2.Property<Guid>("RuleFlagId");

                                    b2.Property<int>("Rule__synthesizedOrdinal");

                                    b2.Property<string>("VariantKey")
                                        .HasMaxLength(128);

                                    b2.HasKey("RuleFlagId", "Rule__synthesizedOrdinal");

                                    b2.ToTable("Flags");

                                    b2.WithOwner()
                                        .HasForeignKey("RuleFlagId", "Rule__synthesizedOrdinal");

                                    b2.OwnsMany("Featly.Split", "Splits", b3 =>
                                        {
                                            b3.Property<Guid>("RuleOutcomeRuleFlagId");

                                            b3.Property<int>("RuleOutcomeRule__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAddOrUpdate();

                                            b3.Property<string>("VariantKey")
                                                .IsRequired()
                                                .HasMaxLength(128);

                                            b3.Property<int>("Weight");

                                            b3.HasKey("RuleOutcomeRuleFlagId", "RuleOutcomeRule__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("Flags");

                                            b3.WithOwner()
                                                .HasForeignKey("RuleOutcomeRuleFlagId", "RuleOutcomeRule__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Splits");
                                });

                            b1.Navigation("Conditions");

                            b1.Navigation("Outcome")
                                .IsRequired();
                        });

                    b.OwnsMany("Featly.Variant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Description")
                                .HasMaxLength(2048);

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(128);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256);

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1.ToJson("Variants");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");
                        });

                    b.Navigation("Rules");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Featly.Segment", b =>
                {
                    b.OwnsMany("Featly.Condition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("SegmentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Attribute")
                                .IsRequired()
                                .HasMaxLength(256);

                            b1.Property<bool>("Negate");

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(32);

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("SegmentId", "__synthesizedOrdinal");

                            b1.ToTable("Segments");

                            b1.ToJson("Conditions");

                            b1.WithOwner()
                                .HasForeignKey("SegmentId");
                        });

                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
