// <auto-generated />
using System;
using System.Collections.Generic;
using Featly.Storage.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Featly.Storage.Postgres.Migrations
{
    [DbContext(typeof(FeatlyDbContext))]
    [Migration("20260703144837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Featly.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("Featly.Flag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DefaultVariantKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("Flags", (string)null);
                });

            modelBuilder.Entity("Featly.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Featly.Flag", b =>
                {
                    b.OwnsMany("Featly.Rule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("Enabled");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .HasMaxLength(256);

                            b1.Property<int>("Order");

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1
                                .ToJson("Rules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");

                            b1.OwnsMany("Featly.Condition", "Conditions", b2 =>
                                {
                                    b2.Property<Guid>("RuleFlagId");

                                    b2.Property<int>("Rule__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Attribute")
                                        .IsRequired()
                                        .HasMaxLength(256);

                                    b2.Property<bool>("Negate");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(32);

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("RuleFlagId", "Rule__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Flags");

                                    b2.WithOwner()
                                        .HasForeignKey("RuleFlagId", "Rule__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Featly.RuleOutcome", "Outcome", b2 =>
                                {
                                    b2.Property<Guid>("RuleFlagId");

                                    b2.Property<int>("Rule__synthesizedOrdinal");

                                    b2.Property<string>("VariantKey")
                                        .HasMaxLength(128);

                                    b2.HasKey("RuleFlagId", "Rule__synthesizedOrdinal");

                                    b2.ToTable("Flags");

                                    b2.WithOwner()
                                        .HasForeignKey("RuleFlagId", "Rule__synthesizedOrdinal");

                                    b2.OwnsMany("Featly.Split", "Splits", b3 =>
                                        {
                                            b3.Property<Guid>("RuleOutcomeRuleFlagId");

                                            b3.Property<int>("RuleOutcomeRule__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<string>("VariantKey")
                                                .IsRequired()
                                                .HasMaxLength(128);

                                            b3.Property<int>("Weight");

                                            b3.HasKey("RuleOutcomeRuleFlagId", "RuleOutcomeRule__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("Flags");

                                            b3.WithOwner()
                                                .HasForeignKey("RuleOutcomeRuleFlagId", "RuleOutcomeRule__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Splits");
                                });

                            b1.Navigation("Conditions");

                            b1.Navigation("Outcome")
                                .IsRequired();
                        });

                    b.OwnsMany("Featly.Variant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("FlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description")
                                .HasMaxLength(2048);

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(128);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256);

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("FlagId", "__synthesizedOrdinal");

                            b1.ToTable("Flags");

                            b1
                                .ToJson("Variants")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FlagId");
                        });

                    b.Navigation("Rules");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
